apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privileged-containers
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: require-non-root
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - app
      validate:
        message: "Pod must run as non-root, at pod or container level."
        anyPattern:
          - spec:
              securityContext:
                runAsNonRoot: true
          - spec:
              containers:
                - securityContext:
                    runAsNonRoot: true

    - name: disallow-escalation
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - app
      validate:
        message: "Containers must not allow privilege escalation or run privileged."
        pattern:
          spec:
            containers:
              - securityContext:
                  allowPrivilegeEscalation: "false"
                  =(privileged): "false"