apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
        app: {{ .Release.Name }}
  policyTypes:
  - Egress

  egress:
  - ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
